# Generated by Django 4.0.3 on 2022-04-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('content', models.TextField()),
                ('issued', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to='upload')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Financial_literacy.author')),
            ],
        ),
    ]
