# Generated by Django 4.0.3 on 2022-04-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
    ]
