# Generated by Django 4.0.3 on 2022-04-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_bikes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='discription',
        ),
        migrations.AddField(
            model_name='bikes',
            name='brand',
            field=models.CharField(blank=True, default='noname', max_length=15, verbose_name='производитель'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='children',
            field=models.BooleanField(blank=True, default=False, verbose_name='детский'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='description',
            field=models.TextField(max_length=50, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='female',
            field=models.BooleanField(blank=True, default=False, verbose_name='женский'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='fork_material',
            field=models.CharField(blank=True, choices=[('a', 'алюминий'), ('s', 'сталь'), ('c', 'карбон')], default='a', max_length=1, verbose_name='материал вилки'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='fork_type',
            field=models.CharField(blank=True, choices=[('h', 'жесткая'), ('a', 'амортизационная')], default='a', max_length=1, verbose_name='тип вилки'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='frame_material',
            field=models.CharField(blank=True, choices=[('a', 'алюминий'), ('s', 'сталь'), ('c', 'карбон')], default='a', max_length=1, verbose_name='материал рамы'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='frame_suspension',
            field=models.BooleanField(blank=True, default=False, verbose_name='задний амортизатор'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='front_brake_type',
            field=models.CharField(blank=True, choices=[('rv', 'ободной: вибрейки'), ('dm', 'дисковые механические'), ('dg', 'дисковые гидравлические'), ('cv', 'ободной клещевой'), ('rg', 'ободные гидравлические'), ('no', 'отсутствует'), ('dr', 'барабанный')], default='rv', max_length=2, verbose_name='передний тормоз'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='front_sprockets',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'одна'), (2, 'две'), (3, 'три')], default=1, verbose_name='звезд спереди'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='gear_type',
            field=models.CharField(blank=True, choices=[('o', 'с внешним переключением'), ('i', 'с планетарной передачей'), ('s', 'синглспид')], default='o', max_length=1, verbose_name='тип трансмиссии'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='image',
            field=models.ImageField(null=True, upload_to='upload', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='in_stock',
            field=models.BooleanField(blank=True, choices=[(True, 'есть в наличии'), (False, 'нет в наличии')], default=True, verbose_name='наличие'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='rear_brake_type',
            field=models.CharField(blank=True, choices=[('rv', 'ободной: вибрейки'), ('dm', 'дисковые механические'), ('dg', 'дисковые гидравлические'), ('co', 'ножной'), ('cv', 'ободной клещевой'), ('rg', 'ободные гидравлические'), ('dr', 'барабанный')], default='rv', max_length=2, verbose_name='задний тормоз'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='rear_sprockets',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='звезд сзади'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='teenage',
            field=models.BooleanField(blank=True, default=False, verbose_name='подрастковый'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='wheel_diameter',
            field=models.PositiveSmallIntegerField(blank=True, default=26, verbose_name='диаметр колес'),
        ),
        migrations.AddField(
            model_name='bikes',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='upload', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='title',
            field=models.CharField(max_length=50, verbose_name='модель'),
        ),
    ]
