# Generated by Django 4.0.3 on 2022-04-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Задайте вопрос')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ на вопрос')),
                ('issued', models.DateTimeField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Введите имя или псевдоним')),
            ],
        ),
    ]
