# Generated by Django 4.0.3 on 2022-04-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='autor',
            new_name='author',
        ),
    ]
