# Generated by Django 4.0.3 on 2022-04-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_autor_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.AddField(
            model_name='question',
            name='author_a',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вы автор ответа! Введите имя или псевдоним'),
        ),
        migrations.AddField(
            model_name='question',
            name='author_q',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вы автор вопроса! Введите имя или псевдоним'),
        ),
    ]
