# Generated by Django 4.0.3 on 2022-04-10 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_question_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='issued',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
