# Generated by Django 4.0.3 on 2022-04-10 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_question_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 21, 7, 13, 632563)),
        ),
    ]
