# Generated by Django 4.0.3 on 2022-04-11 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_question_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='issued',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
