# Generated by Django 4.0.3 on 2022-04-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('price', models.FloatField()),
                ('count', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('count_of_rate', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(to='products.categories')),
            ],
        ),
    ]
