# Generated by Django 4.0.3 on 2022-04-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_authors_products_description_products_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
