# Generated by Django 4.0.3 on 2022-04-10 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок публикации')),
                ('preview', models.CharField(max_length=500, verbose_name='Превью публикации')),
                ('content', models.TextField(verbose_name='Текст публикации')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Время публикации')),
                ('image', models.ImageField(blank=True, upload_to='uploads', verbose_name='Картинка для публикации')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Имя автора комментария')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Время комментария')),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.post')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
